import { Room } from './types.js';

export const rooms: Record<string, Room> = {
  cave: {
    id: 'cave',
    name: 'Dark Cave',
    description: 'You are in a damp cave. Water drips from the ceiling.',
    exits: { north: 'forest', east: 'tunnel', south: 'cavern' },
    items: ['torch'],
    requiresLight: false,
  },
  forest: {
    id: 'forest',
    name: 'Mysterious Forest',
    description: 'Tall trees surround you. Sunlight filters through the leaves.',
    exits: { south: 'cave', east: 'clearing' },
    items: ['wood'],
    requiresLight: false,
  },
  tunnel: {
    id: 'tunnel',
    name: 'Narrow Tunnel',
    description: 'A tight tunnel leads deeper into the mountain.',
    exits: { west: 'cave', east: 'treasure' },
    items: [],
    monster: { name: 'Goblin', health: 5, attack: 2 },
    requiresLight: false,
  },
  treasure: {
    id: 'treasure',
    name: 'Treasure Room',
    description: 'Golden light fills the room. You found the legendary treasure!',
    exits: { west: 'tunnel' },
    items: ['gold'],
    monster: { name: 'Ancient Dragon', health: 20, attack: 5 },
    requiresLight: false,
  },
  cavern: {
    id: 'cavern',
    name: 'Dark Cavern',
    description: 'This cavern is pitch black. You can barely see anything without light.',
    exits: { north: 'cave', east: 'hidden' },
    items: ['stone'],
    requiresLight: true,
  },
  hidden: {
    id: 'hidden',
    name: 'Hidden Chamber',
    description: 'A secret chamber hidden in the darkness. Ancient runes glow faintly.',
    exits: { west: 'cavern' },
    items: ['ancient_key'],
    monster: { name: 'Ghost', health: 10, attack: 3 },
    requiresLight: true,
  },
  clearing: {
    id: 'clearing',
    name: 'Forest Clearing',
    description: 'A peaceful clearing in the forest. Sunlight filters through the canopy, and wildflowers bloom around you.',
    exits: { south: 'forest', east: 'river' },
    items: ['healing_herb'],
    requiresLight: false,
  },
  river: {
    id: 'river',
    name: 'Rushing River',
    description: 'A swift river rushes by. The water is too deep and fast to cross here without proper equipment. You can hear the roar of rapids downstream.',
    exits: { west: 'clearing', south: 'mountain' },
    items: [],
    requiresLight: false,
  },
  mountain: {
    id: 'mountain',
    name: 'Mountain Path',
    description: 'A steep mountain path winds upward. The air is crisp and cool. You can see clouds swirling around the peaks above.',
    exits: { north: 'river', east: 'peak' },
    items: ['rope'],
    monster: { name: 'Mountain Goat', health: 8, attack: 2 },
    requiresLight: false,
  },
  peak: {
    id: 'peak',
    name: 'Mountain Peak',
    description: 'You stand at the mountain peak! The view is breathtaking. Far below, you can see the entire valley laid out before you.',
    exits: { west: 'mountain', south: 'secret' },
    items: ['binoculars'],
    requiresLight: false,
  },
  secret: {
    id: 'secret',
    name: 'Secret Valley',
    description: 'A hidden valley nestled between the mountains. Ancient ruins dot the landscape, hinting at a long-forgotten civilization.',
    exits: { north: 'peak' },
    items: ['ancient_scroll'],
    requiresLight: false,
  },};
